"use strict";

const purgeFromTailwind = (content) => {
	return content.match(/[A-Za-z0-9-_:\/]+/g) || [];
};

module.exports = {
  plugins: {
	  "postcss-import": {},
    tailwindcss: {},
    autoprefixer: {},
	  cssnano: {
		  preset: "default",
	  },
	  "postcss-flexbugs-fixes": {},
	  "postcss-preset-env": {
		  "autoprefixer": {
			  "flexbox": "no-2009"
		  },
		  "stage": 3,
		  "features": {
			  "custom-properties": false
		  }
	  },
	  "@fullhuman/postcss-purgecss": {
		  content: [
			  './pages/**/*.{js,jsx,ts,tsx}',
			  './components/**/*.{js,jsx,ts,tsx}',
			  './styles/**/*',
		  ],
		  extractors: [
			  {
				  extractor: purgeFromTailwind,
				  extensions: ["html", "js", "css"],
			  },
		  ],
		  safelist: {
				standard: [
					"accordion",
					"accordion__button",
					"accordion__panel",
					"center",
					"max-w-full",
					"is-style-with_chevron",
				],
			  deep: [
				  /^ril__/,
				  /m-0$/,
				  /m-1$/,
				  /m-2$/,
				  /m-3$/,
				  /m-4$/,
				  /m-5$/,
				  /m-6$/,
				  /m-8$/,
				  /m-10$/,
				  /m-12$/,
				  /m-16$/,
				  /m-20$/,
				  /m-24$/,
				  /m-32$/,
				  /m-40$/,
				  /m-48$/,
				  /m-56$/,
				  /m-64$/,
				  /m-auto$/,
				  /m-px$/,
				  /my-0$/,
				  /mx-0$/,
				  /my-1$/,
				  /mx-1$/,
				  /my-2$/,
				  /mx-2$/,
				  /my-3$/,
				  /mx-3$/,
				  /my-4$/,
				  /mx-4$/,
				  /my-5$/,
				  /mx-5$/,
				  /my-6$/,
				  /mx-6$/,
				  /my-8$/,
				  /mx-8$/,
				  /my-10$/,
				  /mx-10$/,
				  /my-12$/,
				  /mx-12$/,
				  /my-16$/,
				  /mx-16$/,
				  /my-20$/,
				  /mx-20$/,
				  /my-24$/,
				  /mx-24$/,
				  /my-32$/,
				  /mx-32$/,
				  /my-40$/,
				  /mx-40$/,
				  /my-48$/,
				  /mx-48$/,
				  /my-56$/,
				  /mx-56$/,
				  /my-64$/,
				  /mx-64$/,
				  /my-auto$/,
				  /mx-auto$/,
				  /my-px$/,
				  /mx-px$/,
				  /mt-0$/,
				  /mr-0$/,
				  /mb-0$/,
				  /ml-0$/,
				  /mt-1$/,
				  /mr-1$/,
				  /mb-1$/,
				  /ml-1$/,
				  /mt-2$/,
				  /mr-2$/,
				  /mb-2$/,
				  /ml-2$/,
				  /mt-3$/,
				  /mr-3$/,
				  /mb-3$/,
				  /ml-3$/,
				  /mt-4$/,
				  /mr-4$/,
				  /mb-4$/,
				  /ml-4$/,
				  /mt-5$/,
				  /mr-5$/,
				  /mb-5$/,
				  /ml-5$/,
				  /mt-6$/,
				  /mr-6$/,
				  /mb-6$/,
				  /ml-6$/,
				  /mt-8$/,
				  /mr-8$/,
				  /mb-8$/,
				  /ml-8$/,
				  /mt-10$/,
				  /mr-10$/,
				  /mb-10$/,
				  /ml-10$/,
				  /mt-12$/,
				  /mr-12$/,
				  /mb-12$/,
				  /ml-12$/,
				  /mt-16$/,
				  /mr-16$/,
				  /mb-16$/,
				  /ml-16$/,
				  /mt-20$/,
				  /mr-20$/,
				  /mb-20$/,
				  /ml-20$/,
				  /mt-24$/,
				  /mr-24$/,
				  /mb-24$/,
				  /ml-24$/,
				  /mt-32$/,
				  /mr-32$/,
				  /mb-32$/,
				  /ml-32$/,
				  /mt-40$/,
				  /mr-40$/,
				  /mb-40$/,
				  /ml-40$/,
				  /mt-48$/,
				  /mr-48$/,
				  /mb-48$/,
				  /ml-48$/,
				  /mt-56$/,
				  /mr-56$/,
				  /mb-56$/,
				  /ml-56$/,
				  /mt-64$/,
				  /mr-64$/,
				  /mb-64$/,
				  /ml-64$/,
				  /mt-auto$/,
				  /mr-auto$/,
				  /mb-auto$/,
				  /ml-auto$/,
				  /mt-px$/,
				  /mr-px$/,
				  /mb-px$/,
				  /ml-px$/,
			  ],
		  },
	  },
  },
};
